<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'PerryRylance\\SplitBatch\\Clock' => '/includes/class.clock.php',
                'PerryRylance\\SplitBatch\\Connection' => '/includes/class.connection.php',
                'PerryRylance\\SplitBatch\\Daemon' => '/includes/class.daemon.php',
                'PerryRylance\\SplitBatch\\Job' => '/includes/class.job.php',
                'PerryRylance\\SplitBatch\\Schema' => '/includes/class.schema.php'
            );
        }
        if (isset($classes[$class])) {
            require __DIR__ . $classes[$class];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
